### ISSUE TITLE
1 Do Splash page - add splash page or remove react splash image

### ISSUE THREAD

**Issue by Hillslam** [RMHouseColumbus/rmhc-mobile-app#15]

**Comment by mgersty** [comment]
Updated code base with changes for iOS.  Still need to add splash screen for Android.
Current splash image is temp. Will need to work with UX to get valid images.

**Comment by RMHouseColumbus** [comment]
Add changes for Android as well

**Comment by dnMarc** [comment]
verified change in android simulator (looks like real splash screen) - marking as closed
