### ISSUE TITLE
The following issues were found:

### ISSUE THREAD

**Issue by dnMarc** [RMHouseColumbus/rmhc-mobile-app#29]
Missing colored dots?
Fonts?
Back button?
Rounded?
 
Meals:
Missing?
 
Activities:
Back button?
Rounded?
 
Neighborhood:
Food Delivery Spacing
•      Make the food services hyperlinks instead of link
•      Complete scrolling issues? Footer?
Area Restaurants:
•      Complete scrolling issues? Footer?
•      Header/Title needs capitalized?
Shopping
•      Complete scrolling issues? Footer?
•      Header/Title needs capitalized?
Things To Do:
•      Make the Experience Columbus a hyperlink instead of link
•      Header/Title needs capitalized?
Transportation
•      Make the ride services hyperlinks instead of link
•      Phone number links
 
About:
Spacing of Care Mobile, Share Your Story
Meet the Staff:
•      Currently linked to Food Delivery
Care Mobile:
•      Spacing/Tab
Ways to Stay Involved
•      Spacing/Tab
•      Header/Title size

**Comment by RMHouseColumbus** [comment]
Closing this issue due to the bugs have either been deemed non essential or have been fixed via other issues
