### ISSUE TITLE
Back button in FAQ subpages do have white background in Android

### ISSUE THREAD

**Issue by mgersty** [RMHouseColumbus/rmhc-mobile-app#41]
![image](https://user-images.githubusercontent.com/804411/64398190-ec6c3480-d031-11e9-9809-c68bf93841d9.png)

**Comment by StackTraceYo** [comment]
Ready for Test

**Comment by dnMarc** [comment]
I verified this on my android simulator - the back button is on a blue background as specified in zeplin
