### ISSUE TITLE
svg widths and heights for the footer svgs

### ISSUE THREAD

**Issue by StackTraceYo** [RMHouseColumbus/rmhc-mobile-app#44]
svgs are there for footer but idk what the height and width should be

**Comment by mlbonneville** [comment]
All the icons are 23pt in height. Their widths all be different.

**Comment by RMHouseColumbus** [comment]
Updated widths and viewed on ios and android simulators

**Comment by Vlw-git1** [comment]
Tested with the IPhone 8 Plus and found the footer icons are all sized equally and aligned correctly.  Setting ticket to closed.
