### ISSUE TITLE
Add link to welcome video

### ISSUE THREAD

**Issue by Hillslam** [RMHouseColumbus/rmhc-mobile-app#46]
Here is the link to our welcome video: https://youtu.be/9ypZmfHSiXg

Here is the link to our YouTube channel: https://www.youtube.com/channel/UC64u_BaY1lexz4kCAXpo-1A

**Comment by RMHouseColumbus** [comment]
Can you provide where you would like this welcome video to be on the app?

**Comment by Hillslam** [comment]
Per RMHC please add to Welcome screen. Add the link per the design on the left

<img width="439" alt="Screen Shot 2019-09-19 at 9 55 06 AM" src="https://user-images.githubusercontent.com/4054411/65250709-fd9e5200-dac3-11e9-9229-3c974f67bde1.png">

**Comment by dnMarc** [comment]
I posted in slack - I think this may look different on different simulators...

**Comment by Vlw-git1** [comment]
Using the IPhone 8 Plus the welcome link is present on the home page and correctly goes to the youtube video.  The link is located partially under Henry's thought bubble and will be tracked with ticket #52.  As the link is present and working setting this ticket to closed.
